# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  registry: polls_registry
  DB_HOST: localhost
  DB_USERNAME: postgres
  DB_PASSWORD: postgres

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      image: postgres:latest
      env:
        POSTGRES_DB: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
      ports:
        - 5432:5432
      # Set health checks to wait until postgres has started
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build Postgres:13.2-alpine Docker Image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: "${{secrets.aws_ecr_access_key_id}}"
        password: "${{secrets.aws_ecr_secret_access_key}}"
        registry: "${{env.registry}}"
        image_name: Postgres:13.2-alpine
        context: polls-postgres
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with unittest
      run: |
        cd mysite
        coverage run manage.py test polls
        coverage report --show-missing --fail-under=100